### ISSUE TITLE
Add Coding Standards Section

### ISSUE THREAD

**Issue by Harmos274** [Harmos274/SQA-Assignment#4]
- [x] Select **5 articles** about Coding Standards good practices in **Python 3** and post them as a comment in this issue
- [x] Write down a section about our coding standard in **Python 3** in the `README.md` in the Coding Standards section

**Comment by Harmos274** [comment]
3 articles for coding standards:

General: 
- [SOLID design principles](https://stackify.com/solid-design-principles/)

Python 3:
- [PEP8 Practices with exemples](https://realpython.com/python-pep8/)
- [Structuring your project in Python 3](https://docs.python-guide.org/writing/structure/)

**Comment by BormaPethi** [comment]
Coding Standards Articles:

Definition of testing and best practices:
https://www.testim.io/blog/unit-testing-best-practices/

PEP 8 and SOLID openclassroom:
https://openclassrooms.com/en/courses/6900866-write-maintainable-python-code

Code Unit Tests with Pytest:
https://medium.com/worldsensing-techblog/tips-and-tricks-for-unit-tests-b35af5ba79b1

**Comment by Harmos274** [comment]
Selected articles:


General: 
- [SOLID design principles](https://stackify.com/solid-design-principles/)
- [Definition of testing and best practices](https://www.testim.io/blog/unit-testing-best-practices/)

Python 3:
- [PEP8 Practices with exemples](https://realpython.com/python-pep8/)
- [Structuring your project in Python 3](https://docs.python-guide.org/writing/structure/)
- [Code unit tests with pytest](https://medium.com/worldsensing-techblog/tips-and-tricks-for-unit-tests-b35af5ba79b1)

At the end of the section we can propose to train yourself with [PEP8 and SOLID on openclassroom](https://openclassrooms.com/en/courses/6900866-write-maintainable-python-code)

**Comment by Harmos274** [comment]
Section plan:

1. General knowledge
	1. SOLID Principles - @Harmos274 
	2. Testing practices - @BormaPethi 
2. Python 3
	1.  Project Structure - @Harmos274 
	2. PEP8 - @Harmos274 
	3. Unit Testing - @BormaPethi
