### ISSUE TITLE
Add Code Reviews Section 

### ISSUE THREAD

**Issue by Harmos274** [Harmos274/SQA-Assignment#5]
- [x] Select **5 articles** about code reviews workflow and good practices and post them as a comment in this issue
- [x] Write down a section about our code review workflow in the `README.md` in the Code Reviews section

**Comment by Harmos274** [comment]
3 articles for code reviews:

General:
- [Best practices for peer code review](https://smartbear.com/learn/code-review/best-practices-for-peer-code-review/)
- [Best practices reviewing pull request GitHub](https://www.backhub.co/blog/best-practices-reviewing-pull-requests-github)

Python 3:
- [Python code review checklist](https://deepsource.io/blog/python-code-review-checklist/)

**Comment by Basilarc** [comment]
3 articles for code reviewing (all general) :

- Best practices :https://smartbear.com/learn/code-review/best-practices-for-peer-code-review/
- An other one on best practices but with more informations : https://google.github.io/eng-practices/review/reviewer/
- One last in which author is giving advices based on his own experience : https://stackoverflow.blog/2019/09/30/how-to-make-good-code-reviews-better/

They are obvious similarities between them, but "the devil is in the details".

By the way I didn't think about looking for specifically for python 3, but that was a very good idea. I will try to find one or two especially dedicated to python.

**Comment by Harmos274** [comment]
Selected articles:

General:
- [Best practices for peer code review](https://smartbear.com/learn/code-review/best-practices-for-peer-code-review/)
- [Best practices reviewing pull request GitHub](https://www.backhub.co/blog/best-practices-reviewing-pull-requests-github)
- [Other best practices](https://google.github.io/eng-practices/review/reviewer/)
- [Code review with experience](https://stackoverflow.blog/2019/09/30/how-to-make-good-code-reviews-better/)

Python 3:
- [Python code review checklist](https://deepsource.io/blog/python-code-review-checklist/)

**Comment by Basilarc** [comment]
Introduction - @Basilarc  :

- What is a code review ? What is its purpose ?
- Why doing a code review

Part 1 - @Harmos274 :

- How to do a code review

Part 2 - @Basilarc :

- Common mistakes to avoid
